### ISSUE TITLE
Translation of CAT files

### ISSUE THREAD

**Issue by glixx** [xaos-project/XaoS#103]
CAT files are not standard for translation process. Needs to think about better format. They are near Java properties utf8 format:
key=value
Just to convert them and change code.
As a result they can be translated by transifex.com

**Comment by jblang** [comment]
I have added [cat2prop.py](https://github.com/xaos-project/XaoS/blob/master/catalogs/cat2prop.py) and [prop2cat.py](https://github.com/xaos-project/XaoS/blob/master/catalogs/prop2cat.py) to convert catalog files to and from Java properties files.  I have also attached the 
[english properties file](https://github.com/xaos-project/XaoS/files/3099686/english.txt) here (renamed to english.txt because GitHub would not allow a .properties attachment).  If you can translate this and upload the Russian properties file, I will convert it back to catalog and check it in.

**Comment by glixx** [comment]
Conversion is not equal:
```
python2 ./cat2prop.py english.cat > xaos.properties
python2 ./prop2cat.py xaos.properties > english1.cat
diff -u english1.cat english.cat
--- english1.cat	2019-04-22 03:13:25.373560165 +0300
+++ english.cat	2019-04-22 03:08:58.074738251 +0300
@@ -353,13 +353,11 @@
 incorrectly configured---use `xaos
 -help' for more information),"
 
-#NEW
-emboss1 "an emboss filter,"
+emboss1 "an emboss filter,"  #NEW
 
-#NEW
 palettef1 "a palette emulator filter, 
 (enables color cycling on
-truecolor displays)"
+truecolor displays)"	#NEW
 
 truecolorf "a true color filter, (creates
 true-color images on 8bpp displays)."
@@ -665,11 +663,10 @@
 new4 "4. New in-coloring modes."
 new5 "5. True-color coloring modes."
 new6 "6. Animation save/replay."
-#NEW
 newend "And many other enhancements, such
 as image rotation, better palette
 generation...  See the ChangeLog for
-a complete list of changes."
+a complete list of changes." #NEW
 
 #########################################################
 #For file newton.xaf
```

**Comment by glixx** [comment]
```
> # Tutorial text needs to fit into a 320x200 screen. So all lines must be
> # shorter than 40 characters.  This is 40 characters:
> #234567890123456789012345678901234567890
> # And thats not much! Be careful!
> # Please check that your updated tutorials work in 320x200 to ensure
> # that everything is OK.

```
It's good to have one more script to check strings they are shorter then 40 characters.

**Comment by jblang** [comment]
I intentionally moved the #NEW comments before the line it corresponds to. It's not allowed to have line-end comments on Java properties files.

**Comment by jblang** [comment]
Also, nobody is using a 320x200 screen anymore. That was written back when XaoS was running on DOS.

**Comment by glixx** [comment]
> I can write script to check though.

If do not need to use 40 characters strings, then to delete this info or add comment about DOS.
No needs script if this info is deprecated.

**Comment by glixx** [comment]
Problem is strings in cat file does not follow order, they have random order. So no sense without context.

**Comment by jblang** [comment]
The messages are in the same order they appear in the tutorials. The comments tell you which tutorial .xaf file they come from.  Translators of other languages have been able to figure them out. I have tried to help you by writing the scripts to convert them to properties files, but there is only so much I can do. You seem more interested in pointing out problems than you do in doing an actual translation.

**Comment by glixx** [comment]
Not each language has declensions, conjugations and genders, when the next sentence depends on the previous one.

**Comment by jblang** [comment]
Well, in the cat file at least, I believe they should be in order presented in the tutorials, and my script does not change the order in the property files. Maybe Transifex isn't keeping them in order when displaying them.

You can also grep for message in the .xaf files and that will show you the order the message keys are displayed in, if there is any doubt.  I'm sorry, I don't really know what else I can do to improve the situation short of rewriting the entire tutorial system, and I don't think that's something I can take on right now.

**Comment by glixx** [comment]
Thanks for scripts.
