### ISSUE TITLE
Hide Qt menu bar

### ISSUE THREAD

**Issue by trathborne** [xaos-project/XaoS#111]
I like to run XaoS full screen and the Qt menu bar is distracting. In the old X11 GUI, the menu bar would only appear when the cursor hit the top of the screen.

**Comment by alspore** [comment]
I would like to be able to hide the menu bar as well, otherwise I have to crop fullscreen screenshots.

**Comment by jblang** [comment]
I just checked this in. There's now a Fullscreen option in the View menu and when activated, the menu bar automatically hides unless the mouse is at the top of the screen.  We're going to release a new preview build soon.

**Comment by trathborne** [comment]
Awesome! Many thanks!
