### ISSUE TITLE
Incorrect handling of numeric localization

### ISSUE THREAD

**Issue by jblang** [xaos-project/XaoS#120]
In my locales where the decimal separator is a comma, XaoS does not parse numerical strings correctly.  Qt validation requires numbers to be entered with a comma (e.g. at Zooming speed), but XaoS parsing code then expects the number to contain a decimal point, and it is not translated correctly to a number. So I get 0 immediately after conversion.

**Comment by jblang** [comment]
@kovzol I think this may be fixed now. I am not using the Qt numeric formatting functions anymore. Can you try it and let me know?

**Comment by kovzol** [comment]
Yes, now it works nicely. Thanks!
