### ISSUE TITLE
Allow selecting from a list of user formulas

### ISSUE THREAD

**Issue by kovzol** [xaos-project/XaoS#123]
This would be useful for new-comers to learn the syntax of user formulas, and also to provide more examples immediately. Also, the list could be saved for the next startup of XaoS as well. See http://rtzme.sourceforge.net/english.php for some idea how this could be implemented.

**Comment by kanurag94** [comment]
There are two approaches on how to implement this:

1. Use a ```.useformulasXaoS``` file and save all formulas there separated by a new line in format as
```
formula1 forumula1_name
formula2 formula2_name
````

2. Create individual files for formula in a directory user_formulas and save them in a format as
```
Name: Formula_name
Created_on: 21/09/2020
Author: Superman
# Formula starts after this line
myformula keeps on going and
extends to multiple lines
```

I am inclined towards approach 2 considering we may have support for multi line formulas someday.

What do you think?

**Comment by kovzol** [comment]
I think currently it's OK to have just a list of user formulas saved in the ~/.config/XaoS\ Project/XaoS.conf file (see QSettings), maybe just an array of strings and nothing more. Later we can do something better by sharing formulas with other users, but for that we need much more.
