### ISSUE TITLE
Lag in render and random palette

### ISSUE THREAD

**Issue by AndyB122** [xaos-project/XaoS#127]

**Comment by jblang** [comment]
Can you give more details?

**Comment by AndyB122** [comment]
This is a video of what i get on v4 beta using a random render i then zoom in to a part i like at which point i want to change the palette and i find a random palette using the shortcut key p works well . All is good up until i then save and continuing the zoom to find another picture at this point rendering seems to lag where as in v3.4 it never .... Again i will use p to change the palette and i find a break down in the zoom but not the palette !

Sorry but the video is to large to attach 110 Mb and that is the smallest i can get it ......

**Comment by jblang** [comment]
I saw the video you posted on Facebook.  It looks like you are zoomed in as far a XaoS can go. This is a limitation of the 80-bit math used by the CPU. You can press `l`, which will display the status. It will tell you "zoomed xxxxxxxxxxxxxxxxxxxx.xx times (yy.yE)". If you go past 16.0E, you will start to see the image get blocky and eventually you won't be able to zoom in anymore. There is a way to compile XaoS with 128-bit math, which will let you zoom in further (32.0E), but it's much slower.

That shouldn't be different than 3.4 though.  Are you sure you were zoomed into the same place in both versions?  Again, try pressing `l` to display mini status and check how far you're zoomed in. If it's over ~16E, then it is expected behavior for you to no longer be able to zoom any further.

**Comment by AndyB122** [comment]
I have done as you said and it is not the 1 zoom error as you suggested 3.4 zooms in more after the setting is reached on 4.0 Beta ! I am so sorry to say that i wanted you to be right ! On 3.4 i could keep on zooming in without problems ..... 4.0 Beta rendering is definitely slower for some reason and then lags around the 4th render especially if i use the random render  ! Thoughts .... ?

**Comment by jblang** [comment]
Can you take a screenshot of both 3.4 and 4.0 zoomed into the same location, with both Mini Status and Status enabled on the view menu?

**Comment by AndyB122** [comment]
Will do my friend .

**Comment by AndyB122** [comment]
These are the best i can do v3.4 is the first one and i could keep going where as v4 beta (second) i started to run into problems rendering speed and zoom !
![New Picture (3)](https://user-images.githubusercontent.com/59623057/72093337-17320680-330c-11ea-843c-225aadb5b999.jpg)
![New Picture (6)](https://user-images.githubusercontent.com/59623057/72093362-1e591480-330c-11ea-9422-b17e79a88dbf.jpg)

**Comment by jblang** [comment]
I'm sorry, I'm not really able to tell what's going on from what you have given me so far.  I don't know, maybe you can zoom to a location that it is about to start messing up and save the location (.xpf file).  Confirm that you can get the problem to occur in that area, close XaoS, open back up and reload the file to see if you can get the same behavior again.  If so, then send the xpf file to me and maybe I will be able to reproduce it.

**Comment by jblang** [comment]
Actually, I was able to find the same location by entering the coordinates that you showed in your screenshot.  See my screenshot. I am able to continue zooming in, change the palette, and do whatever else without experiencing any lag.  Does it always happen at the same locations or is it random?

![image](https://user-images.githubusercontent.com/947942/72118109-be676b80-3315-11ea-83a4-19898ed07611.png)

**Comment by AndyB122** [comment]
After 4 renders the lag kicks in but i can still (as you say) keep changing the palette etc . So it is as you said Random !

**Comment by AndyB122** [comment]
I will do the .xpf idea next time i use it ..... Thanks.

**Comment by AndyB122** [comment]
Tried your suggestion after loading new patch and managed to zoom in to pic 1 max ..... second attempt took the .xpf  and rechecked no problems ! Maximum lag seems to be rendering a really complex fractal but that is expected Mandelbulb3D.exe is terrible for it ! 
![New Picture (15)](https://user-images.githubusercontent.com/59623057/72178948-f3d68c80-33db-11ea-93d3-481664dfd282.jpg)

**Comment by AndyB122** [comment]
Think you have solved it for me my friend ! Thanks .....

**Comment by jblang** [comment]
I'm not sure I follow exactly, but I am glad you found a way around it. I am still not able to reproduce anything like this.  When you say "After 4 renders the lag kicks in" do you mean renders using the File->Render Animation command, or are you just talking about zooming fractals with XaoS?
