### ISSUE TITLE
Generate image with different dimensions than the screen.

### ISSUE THREAD

**Issue by rquadling** [xaos-project/XaoS#135]
Is it possible to create an image that is for a different set of dimensions to the screen?

I'd like to create 5000x1200 pixel images.

I'd be happy with a "letterbox" mode to be able to visualise and select the image.

**Comment by jblang** [comment]
Yes, it is possible. Use File->Save to save the parameters as an xpf file. Then use File->Render and select the xpf file you saved, and give the name for an output file. Enter the resolution you want, and click OK. Any other settings can be left alone.
