### ISSUE TITLE
XaoS does not contain any version numbers on macOS

### ISSUE THREAD

**Issue by core-code** [xaos-project/XaoS#136]
<img width="262" alt="Screenshot 2020-02-15 at 08 17 43" src="https://user-images.githubusercontent.com/1261954/74591311-cfb62e80-4fcb-11ea-9eef-05c75a4ecfff.png">

the CFBundleVersion and CFBundleShortVersionString entries in your Info.plist file are missing.

additionally the CFBundleGetInfoString entry should be removed - it has been deprecated for more than 10 years

**Comment by jblang** [comment]
This is not something we have direct control over as far as I know. We now use Qt to build XaoS for all OSes and the metadata for the executable is whatever is automatically set by the Qt build scripts.

**Comment by core-code** [comment]
this is quite easy to fix even with Qt
