### ISSUE TITLE
Fractal only fills one quarter of app window on Retina display in macOS

### ISSUE THREAD

**Issue by mcpgv** [xaos-project/XaoS#137]
Pixel scaling on macOS with Retina display is incorrect - fractals only fill one quarter of the application window, although clicking behaves as if the fractal was scaled to fill the whole window.

XaoS 4.0pre2 on MacBook Pro 13-inch 2017 running macOS Catalina 10.15.3

<img width="1072" alt="Screenshot 2020-03-08 at 11 25 49 pm" src="https://user-images.githubusercontent.com/61952138/76173104-26aac000-6194-11ea-9c70-c8885157af91.png">

**Comment by jblang** [comment]
Have you tested this with 4.0pre4?

**Comment by mcpgv** [comment]
Apologies - it seems to work fine on 4.0pre4.

For some reason I thought I had the latest version with 4.0pre2 (I only downloaded it three days ago - the link I used obviously did not take me to the latest version).

Regards,

Paul

**Comment by jblang** [comment]
Where was the link that you used? I will try to correct it if I can.

**Comment by mcpgv** [comment]
It’s the “experimental prerelease for 4.0” link at http://matek.hu/xaos/doku.php?id=downloads:main <http://matek.hu/xaos/doku.php?id=downloads:main> which points to the specific 4.0pre2 release (https://github.com/xaos-project/XaoS/releases <https://github.com/xaos-project/XaoS/releases>) rather than all the releases with the latest at the top (https://github.com/xaos-project/XaoS/releases/tag/4.0pre2 <https://github.com/xaos-project/XaoS/releases/tag/4.0pre2>)

**Comment by mcpgv** [comment]
It’s the “experimental prerelease for 4.0” link at [GNU XaoS - Downloads](http://matek.hu/xaos/doku.php?id=downloads:main) which points to the specific [4.0pre2 release](https://github.com/xaos-project/XaoS/releases/tag/4.0pre2) rather than [all releases](https://github.com/xaos-project/XaoS/releases) with the latest at the top.

**Comment by jblang** [comment]
Thanks, I've fixed the link on the page. I'll close this now.
