### ISSUE TITLE
Add translation for new strings

### ISSUE THREAD

**Issue by cvermot** [xaos-project/XaoS#144]
Hi everybody,

Which method do you use for .ts files updating when you add some strings to translate ? I add some TR() call, but when I run ludpate from Qt Creator, the old translations are lost because locations are lost in the .ts file

example :
  ```
 <message>
        <location filename="../src/ui-hlp/menu.cpp" line="105"/>
        <source>Perturbation:</source>
        <translation type="unfinished">Perturbation :</translation>
    </message>
```
became
   ```
<message>
        <source>Perturbation:</source>
        <translation type="obsolete">Perturbation :</translation>
    </message>
```
-> translation files are corrupted and translation of the application didn't work anymore.

I found that TR() is a macro aimed to translate XaoS's world strings to Qt's world, is it anything else to do before running lupdate ? I didn'f find anything in the documentation !

**Comment by kovzol** [comment]
Does the explanation in the file https://github.com/xaos-project/XaoS/blob/master/i18n/README.md not help?

**Comment by cvermot** [comment]
Seems to be what I need ! I will try it soon ! Thank you !

**Comment by cvermot** [comment]
It works ! I created a new pull request => cvermot:missingTranslation
