### ISSUE TITLE
Archaic references

### ISSUE THREAD

**Issue by arm-in** [xaos-project/XaoS#149]
Some references in the tutorial seem to be outdated:

catalogs/en.cat
* 130Mhz Pentium
* high color display (this is 15bpp or 16bpp)
* 8bpp display

Keep for historical view? Replace with modern pendant?

**Comment by kovzol** [comment]
This piece of text belongs to the section "What's new in 3.0"? Now we also have a short "What's new in 4.0?", it could be extended in case. Actually I think we should keep the old texts for historical view.

**Comment by arm-in** [comment]
OK, sounds reasonable.
