### ISSUE TITLE
Command line: Invalid commands should produce syntax error

### ISSUE THREAD

**Issue by kanurag94** [xaos-project/XaoS#155]
Currently command line functionality in xaos is difficult to use, mostly since it doesn't produce any warning/error on use of wrong syntax. We should be able to start checking command syntax and produce warnings and help messages accordingly.

I am using a Ubuntu 20.04 install with Qt build from source

**Comment by kanurag94** [comment]
Some more information:

The issue seems to be with how XaoS is handling empty file path and examples file path. 
I couldn't ```Load Random Example``` and starting recording from XaoS startup also produces same error.

XaoS handles these paths using https://github.com/xaos-project/XaoS/blob/master/src/include/xio.h#L50-L52, which gets changed when we select a directory with some other path, thus no error there.

**Comment by kovzol** [comment]
I assume you mean the command line interface and also the commands that are available in the Action > Command... menu.
1. The command line interface already exists if you enter a command that cannot be recognized. But immediately after then the whole help is shown (that can be invoked by `xaos -help`). I think this is not very convenient, so maybe XaoS should not show more message than like this:
```xaos -h
h:unknown function, please enter "xaos -help" to learn more on command line options
```
Note that currently the first part ("h: unknown function") is working, and printed to stderr. I think this is acceptable. Also, maybe we want to avoid printing other types of debug information. I am unsure if they are only available in the DEBUG build. For a DEBUG build this is OK.
2. I confirm that there should be some error message given if the command given in via the Action > Command... menu. The error message could be somewhat the same as shown via the command line interface. So, they should be handled in a somewhat unified way.

**Comment by kanurag94** [comment]
> I am unsure if they are only available in the DEBUG build

Yes they are only available in DEBUG build.
I have done changes for 1 - https://github.com/xaos-project/XaoS/commit/c2bd042ef10fa29e382f69ce2f78d30ead87e6ba

I will try to work on 2 in next few days.

**Comment by kovzol** [comment]
Very good, thanks!
