### ISSUE TITLE
Consider unifying some menu options

### ISSUE THREAD

**Issue by kovzol** [xaos-project/XaoS#190]
The amount of options in the File menu can be confusing for some users. We may consider using only one option for the following ones:
* Open... and Open image... Here we can offer the file extensions *.xpf and *.png together. Depending on the chosen file type the need loader function could be triggered.
* Save... and Save image... Similarly to the above mentioned idea.
I am unsure what technical difficulties can be faced on the programming side.

**Comment by kanurag94** [comment]
I think both are possible. But unifying save can be confusing.
Something like this could be done  -: 
1. Unify Open and Open Image
2. Rename ```Save``` to ```Save as``` and have sub-menu options to save as xpf or image. Or we can just have save (the official XaoS format i.e. xpf) and save as that could have sub options to save as png, tiff etc. formats.

This is implemented in almost all major programs, for example gimp, libreoffice word etc.

**Comment by kovzol** [comment]
I like both ideas!
