### ISSUE TITLE
Save palette information to xpf

### ISSUE THREAD

**Issue by kanurag94** [xaos-project/XaoS#196]
XaoS xpf are position files which track palette currently using seed, shift and algorithm number value. After #195 #194 and #192 the ability to set custom palette was introduced. This should be saved to xpf only.

**Comment by kanurag94** [comment]
Palette picker currently uses the first 31 colors to create a palette again using the chosen colors. While this is perfect for palette with seed, type, shift set to default or 0. This will fail to save information for palettes with these values set. The loaded palette will have somewhat different segments. 
The first 31 colors are randomized throughout 65534 colors & we could not possibly know the colors to pick for creating palette configuration file (.gpl).
The possible solution is to save all the colors (65534 colors). This will block this issue.

**Comment by kovzol** [comment]
How about with the following idea?
We should save the "default" palette only if the user changed the palette entries (or loaded a .gpl file).
Maybe a command `(palettecolors 000000 01020f 210012 ...)` could be useful.

**Comment by kanurag94** [comment]
Thanks. I implemented this in the above PR.
