### ISSUE TITLE
xaos-3.6/src/include/xmenu.h:337: bad macro ?

### ISSUE THREAD

**Issue by dcb314** [xaos-project/XaoS#206]
xaos-3.6/src/include/xmenu.h:337:29: warning: division 'sizeof (menuitem *) / sizeof (menuitem)' does not compute the number of array elements [-Wsizeof-pointer-div]
  337 | #define NITEMS(n) (sizeof(n)/sizeof(menuitem))
      |                             ^
ui.c:1034:25: note: in expansion of macro 'NITEMS'
 1034 |     menu_add(menuitems, NITEMS(menuitems));
      |                         ^~~~~~
ui.c:954:18: note: first 'sizeof' operand was declared here
  954 | static menuitem *menuitems;
      |                  ^~~~~~~~~

**Comment by kovzol** [comment]
It does. I debugged every instance. I think it is a false warning for this case, I think this is an issue in the compiler.
