### ISSUE TITLE
Dependency error in Linux Mint on libdrm2-amdgpu

### ISSUE THREAD

**Issue by retrue** [xaos-project/XaoS#211]
**Describe the bug**
I am using a fresh installation of Linux Mint 20.1, a fork of Ubuntu 20.04. When trying to install the last deb package in the releases section of this web I get the message (translating from Spanish):
Error: The dependency on libdrm2-amdgpu (>=1:2.4) could not be satisfied.

**Expected behavior**
To install the deb package without problems. The version available in the repositories is very old (version 3.5)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1 (based on Ubuntu 20.4)

**Additional context**
Checking Sypnatic I see that libdrm2-amdgpu1 version 2.4.102-1ubuntu1~20.04.1 is installed. That is the last version of the library and I have the sensation that libdrm2-amdgpu and libdrm2-amdgpu are the same library with different names.

**Comment by kovzol** [comment]
Thanks for the report! I think the problem is that I compiled the package on specific hardware. I will recompile the package on a fresh Ubuntu 20.04 install and upload a fixed version.

**Comment by kovzol** [comment]
I removed the old version and uploaded a new one. Please try the new version!

**Comment by retrue** [comment]
Thanks for the quick solution. It works now.
