### ISSUE TITLE
What is needed to create a macOS app bundle?

### ISSUE THREAD

**Issue by szhorvat** [xaos-project/XaoS#212]
As someone not experienced with Qt, I would like to know what is needed to create a macOS app bundle similar to the one downloadable from the releases. Simply using `qmake` then `make` creates a working app bundle, but it lacks the `examples`, `tutorial` and `catalogs` directories. Moreover, the structure of the `examples` directory in the official app bundle is not the same as in the git repo. What must one do to create a complete app bundle? I assume manually copying the files is not the correct way.

**Comment by kovzol** [comment]
Szabolcs, you need to run the script `tools/deploy-mac`.

**Comment by szhorvat** [comment]
Thank you!

**Comment by szhorvat** [comment]
@kovzol XaoS is now updated to 4.2.1 in MacPorts (used to be on version 3.6).

**Comment by kovzol** [comment]
@szhorvat Very nice, thanks!
