### ISSUE TITLE
Does not compile wit Qt 5.6

### ISSUE THREAD

**Issue by szhorvat** [xaos-project/XaoS#215]
The .pro file indicates that the minimum Qt version is 5.6, but in fact it does not compile with this version. Qt 5.7 seems to be necessary.

https://github.com/xaos-project/XaoS/blob/master/XaoS.pro#L6

The error is 

```
src/ui/main.cpp:470:49: error: no member named 'DefaultNumberOptions' in 'QLocale'
    QLocale::system().setNumberOptions(QLocale::DefaultNumberOptions);
                                       ~~~~~~~~~^
```

See https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/50936/steps/install-port/logs/stdio

I suggest updating the minimum requirements to Qt 5.7.

**Comment by szhorvat** [comment]
It's here in 5.7:

https://github.com/qt/qtbase/blob/5.7/src/corelib/tools/qlocale.h#L895

But not 5.6:

https://github.com/qt/qtbase/blob/5.6/src/corelib/tools/qlocale.h#L845

**Comment by kovzol** [comment]
Thanks for reporting this issue!
