### ISSUE TITLE
qmake does not define STRIP

### ISSUE THREAD

**Issue by Rhialto** [xaos-project/XaoS#217]
**Describe the bug**
When qmake generates the Makefile, it leaves the definition of `STRIP` empty.

**To Reproduce**
1. qmake
2. gmake
3. get weird errors because make tries to run `bin/xaos` which fails, because the build environment has no $DISPLAY.
4. The executed line is `$(STRIP) $(TARGET)` and `$(STRIP)` is empty.
4. The line that should define it reads, in full, 
```
STRIP         =
```

**Expected behavior**
qmake should find the `strip` command, which is available, and define `STRIP` accordingly.

**Desktop (please complete the following information):**
 - OS: NetBSD
 - Version 9.2

**Additional context**
I ran into this while trying to package XaoS 4.2.1 for pkgsrc.
I have no experience with qmake so I have no idea where to search for this. Grepping for STRIP gave no clue.

**Comment by kovzol** [comment]
Thanks for reporting this! I think this is more a Qt related problem since this is not an issue on the supported platforms.
I guess NetBSD 9.2 uses Qt 6.1.1, please confirm. We did not try to compile with XaoS with Qt 6 yet, only Qt 5 is officially supported.

**Comment by Rhialto** [comment]
Thanks for looking at it. Alas, I'm using Qt 5.15.2.

From the Makefile:
```
#############################################################################
# Makefile for building: bin/xaos
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  XaoS.pro
# Template: app
# Command: /usr/pkg/qt5/bin/qmake -o Makefile XaoS.pro
#############################################################################
```

I grepped around for `STRIP` in `/usr/pkg/qt5/mkspecs/` and I found lots of refrences to `QMAKE_STRIP`, for example in `/usr/pkg/qt5/mkspecs/common/bsd/bsd.conf` but also e.g. in `/usr/pkg/qt5/mkspecs/common/linux.conf`.

Getting optimistic by this find, I changed `QMAKE_POST_LINK=$(STRIP) $(TARGET)` in `XaoS.pro` to use `QMAKE_STRIP` instead. That didn't help though. I was hoping that the use of `$(STRIP)` was the thing that triggered the inclusion of `STRIP =` in the Makefile; apparently that is not how it works, because nothing changed there. And since `QMAKE_STRIP` was totally undefined in the Makefile, that didn't bring me any closer.

In the `Makefile` I found this dependency list, which looks like it includes all files that qmake considers when generating the Makefile.
```
Makefile: XaoS.pro /usr/pkg/qt5/mkspecs/netbsd-g++/qmake.conf /usr/pkg/qt5/mkspecs/features/spec_pre.prf \
                /usr/pkg/qt5/mkspecs/common/sanitize.conf \
                /usr/pkg/qt5/mkspecs/common/gcc-base.conf \
                /usr/pkg/qt5/mkspecs/common/gcc-base-unix.conf \
                /usr/pkg/qt5/mkspecs/common/g++-base.conf \
                /usr/pkg/qt5/mkspecs/common/g++-unix.conf \
                /usr/pkg/qt5/mkspecs/common/unix.conf \
                /usr/pkg/qt5/mkspecs/qconfig.pri \
```
and a whole lot under `/usr/pkg/qt5/mkspecs/modules` and `.../features` and also some from the XaoS sources. The list looks pretty sensible to me.

However the files that define `QMAKE_STRIP` don't seem to be in the list. Not knowing qmake I don't know if they should be, or if there is some option to include them, or what.
Perhaps it should not be including `common/unix.conf` but `common/bsd/bsd.conf` instead, because this one includes the other, and it does define `STRIP`. But I don't know where this is configured (maybe even when qmake is built?)

Still, I'm wondering where the template of the `Makefile` comes from. I hope it isn't just compiled into the qmake executable; but I could not find some key phrases from it when I grepped through the XaoS source and `/usr/pkg/qt5/mkspecs`.

For reference, when running qmake, `PATH=/tmp/pkgsrc/x11/XaoS/default/.cwrapper/bin:/tmp/pkgsrc/x11/XaoS/default/.buildlink/bin:/tmp/pkgsrc/x11/XaoS/default/.gcc/bin:/tmp/pkgsrc/x11/XaoS/default/.tools/bin:/usr/pkg/bin:/usr/pkg/bin:/usr/pkg/sbin:/bin:/sbin:/usr/bin:/usr/sbin` and there exist `/usr/bin/strip` and I can cause `/tmp/pkgsrc/x11/XaoS/default/.tools/bin/strip` to exist as well.

If everything else fails, if there is some option or environment variable I could use to forcefully override the definition of `STRIP`, that would work for me. Right now I'm using `sed` to edit the `Makefile` so it would be an improvement :)

**Comment by Rhialto** [comment]
Right, it is a qmake issue. The file that initially gets included is `/usr/pkg/qt5/mkspecs/netbsd-g++/qmake.conf` and it includes `include(../common/unix.conf)`. If I replace that by `include(../common/bsd/bsd.conf)`, then `STRIP` gets defined (even though the newly included file only references `QMAKE_STRIP`, but apparently that's good enough.

I'm now looking at how to get this fixed in pkgsrc, and I'm getting confused again, since the source file (in qt5-qtbase) `qtbase-everywhere-src-5.15.2/mkspecs/netbsd-g++/qmake.conf` doesn't quite seem to correspond to the installed file `/usr/pkg/qt5/mkspecs/netbsd-g++/qmake.conf`. In particular it does seem to include the right `include` statement...

But that is something I'll have to discuss with the pkgsrc team I think.

Thanks again for your time for this!

**Comment by kovzol** [comment]
Thanks for checking!
