### ISSUE TITLE
Loading a random example does not work on Ubuntu 21.10

### ISSUE THREAD

**Issue by rolandog** [xaos-project/XaoS#225]
**Describe the bug**
Clicking on `File > Load random example` results in an error message displaying `Error: Could not open examples` .

**To Reproduce**
1. Go to 'File'
2. Click on 'Load random example'
3. See error

**Expected behavior**
A random example loads.

**Screenshots**
![Screenshot from 2021-11-29 12-14-57](https://user-images.githubusercontent.com/12400926/143858309-cf0b8e7a-6c3d-434c-a827-36cc9de2435f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - XaoS Version: 4.2.1

**Additional context**
I tried both removing and reinstalling, as well as completely removing (including configuration files) and reinstalling.  It could be related to #83.

**Comment by kanurag94** [comment]
@rolandog Is the behaviour same on earlier ubuntu versions. Also can you try building from sources?

**Comment by rolandog** [comment]
Hey @kanurag94 , thanks for your response.

I would've sworn I ran into the same issue when running on 20.10 at the beginning of this year.  But I only tried XaoS for a short while and I didn't have the time to submit a bug back then.  Since then, I have upgraded Ubuntu to 21.04 and then to 21.10, and had a bit more time to play with XaoS.

<details>
<summary>Here's the output of `zgrep` on `dpkg` logs:</summary>

``` console
rolandog@computer:~$ zgrep -i 'XaoS' /var/log/dpkg.log*
/var/log/dpkg.log.1:2021-11-29 12:08:09 upgrade xaos:amd64 4.2.1-2 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:08:09 status half-configured xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:08:09 status unpacked xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:08:09 status half-installed xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:08:09 status unpacked xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:08:10 configure xaos:amd64 4.2.1-2 <none>
/var/log/dpkg.log.1:2021-11-29 12:08:10 status unpacked xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:08:10 status half-configured xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:08:10 status installed xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:12:55 status installed xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:12:55 remove xaos:amd64 4.2.1-2 <none>
/var/log/dpkg.log.1:2021-11-29 12:12:55 status half-configured xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:12:55 status half-installed xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:12:55 status config-files xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:12:55 status not-installed xaos:amd64 <none>
/var/log/dpkg.log.1:2021-11-29 12:13:15 install xaos:amd64 <none> 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:13:15 status half-installed xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:13:15 status unpacked xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:13:15 configure xaos:amd64 4.2.1-2 <none>
/var/log/dpkg.log.1:2021-11-29 12:13:15 status unpacked xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:13:15 status half-configured xaos:amd64 4.2.1-2
/var/log/dpkg.log.1:2021-11-29 12:13:15 status installed xaos:amd64 4.2.1-2
/var/log/dpkg.log.10.gz:2021-02-24 00:30:19 install xaos:amd64 <none> 4.1-1
/var/log/dpkg.log.10.gz:2021-02-24 00:30:19 status half-installed xaos:amd64 4.1-1
/var/log/dpkg.log.10.gz:2021-02-24 00:30:19 status unpacked xaos:amd64 4.1-1
/var/log/dpkg.log.10.gz:2021-02-24 00:30:19 configure xaos:amd64 4.1-1 <none>
/var/log/dpkg.log.10.gz:2021-02-24 00:30:19 status unpacked xaos:amd64 4.1-1
/var/log/dpkg.log.10.gz:2021-02-24 00:30:19 status half-configured xaos:amd64 4.1-1
/var/log/dpkg.log.10.gz:2021-02-24 00:30:19 status installed xaos:amd64 4.1-1
/var/log/dpkg.log.3.gz:2021-09-08 08:56:03 upgrade xaos:amd64 4.1-1 4.2.1-2
/var/log/dpkg.log.3.gz:2021-09-08 08:56:03 status half-configured xaos:amd64 4.1-1
/var/log/dpkg.log.3.gz:2021-09-08 08:56:03 status unpacked xaos:amd64 4.1-1
/var/log/dpkg.log.3.gz:2021-09-08 08:56:03 status half-installed xaos:amd64 4.1-1
/var/log/dpkg.log.3.gz:2021-09-08 08:56:03 status unpacked xaos:amd64 4.2.1-2
/var/log/dpkg.log.3.gz:2021-09-08 11:30:37 configure xaos:amd64 4.2.1-2 <none>
/var/log/dpkg.log.3.gz:2021-09-08 11:30:37 status unpacked xaos:amd64 4.2.1-2
/var/log/dpkg.log.3.gz:2021-09-08 11:30:37 status half-configured xaos:amd64 4.2.1-2
/var/log/dpkg.log.3.gz:2021-09-08 11:30:37 status installed xaos:amd64 4.2.1-2
```

</details>

As for building, do you want me to try to build on a particular tagged branch?

**Comment by kovzol** [comment]
Same on Ubuntu 22.04 (daily build), I think it is worth reporting to Ubuntu (or Debian) maintainers directly, because this should have been fixed in the sources (on the main branch).

**Comment by leahneukirchen** [comment]
I don't get this fix at all, and also release 4.3 hangs here.

https://github.com/tabhishek432/XaoS/commit/67a9c261479e5dc70db9704d468c99d65725aeef#diff-7c8e040d1982db3517521e9ab5d9769e8872ea89aa5028946395215d51c1c21bR174 tries to read `../examples` (from current pwd) and the whole thing just hangs if that directory doesn't exist.

**Comment by kovzol** [comment]
You seem to be right, I'll try to fix this asap.

**Comment by kovzol** [comment]
I guess I fixed this.

**Comment by leahneukirchen** [comment]
Works, thanks!
