### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by adammaj1** [xaos-project/XaoS#234]
Hi

Here are 2 xpf files for [the parabolic Julia set for f(z)=z^5+m*z^4+z where m = 0.8+0.4*i](https://commons.wikimedia.org/wiki/File:Parabolic_Julia_set_for_f(z)%3Dz%5E5%2Bm*z%5E4%2Bz_where_m_%3D_0.8%2B0.4*i.png)
```
 (initstate)
 (defaultpalette 0)
 (formula 'user)
 (usrform "(Z^5)+((0.8+0.4i)*(Z^4))+Z")
 (usrformInit "")
 (view -0.212 -0.847 4.04 4.04)
```
This gives inverted image. I think that it is a bug
```
 (initstate)
 (defaultpalette 0)
 (formula 'user)
 (usrform "(Z^5)+((0.8+0.4I)*(Z^4))+Z")
 (usrformInit "")
 (periodicity #f)
 (incoloring 2)
 (view -0.4444 0.09005 3.798 3.798)
```
Here one can see 3 repelling petals

See also [commons category : Fractal created with XaoS](https://commons.wikimedia.org/wiki/Category:Fractals_created_with_Xaos)

HTH

Adam

**Comment by kovzol** [comment]
Thanks for your contributions (and sorry for the long delay)! Yes, maybe the fractal is shown mirrored, this may be a bug, indeed.
Please feel free to submit further fractals with their XPF files by forking the code and using a pull request if possible. Thanks!
