### ISSUE TITLE
GSoC Contributors

### ISSUE THREAD

**Issue by FantasyPlanet** [xaos-project/XaoS#238]
Hello, I have submitted my proposal. If you have any questions about me, please contact me by email. If my proposal is not specific enough or needs to be modified, please feel free to contact me. Looking forward to your reply.
XaoS has a Qt interface, but to use it, end users require to download and install the software. The current version of XaoS is malfunctioning on the web platform because of a non-conform way of the implementation of realtime animation. I will work on fixing these potential bugs to keep XaoS working properly on the web.I will find the source of the problem by comparing the implementation of animation between the QT version and the web version, and modify the code of the web version to ensure its normal operation on the web and avoid failures.

**Comment by kovzol** [comment]
Hi, sorry for the late answer. Thank you --- meanwhile we chose another student. Please feel free to contribute if you have some further ideas.
