### ISSUE TITLE
Missing INSTALL_ROOT in qmake installation

### ISSUE THREAD

**Issue by atsampson** [xaos-project/XaoS#240]
Thanks for adding the qmake install rules in version 4.3 - that's made life much simpler for packagers!

The custom install rule for the examples is currently written like this:

```
examples.extra = find examples -name \'*.xpf\' -exec cp {} $$PREFIX/share/XaoS/examples \;
```

This doesn't work if you've set `INSTALL_ROOT` (qmake's equivalent of what most build systems call `DESTDIR`) to install into a staging dir. Writing it this way generates a correct Makefile rule and fixes the problem for me:

```
examples.extra = find examples -name \'*.xpf\' -exec cp {} $(INSTALL_ROOT)$$PREFIX/share/XaoS/examples \;
```

It's not immediately obvious to me from the qmake docs whether you're allowed to refer to its make variables like this, though...

**Comment by kovzol** [comment]
Thanks for this comment. Please do some research if this is widely used by others, that is, if it is at least a de facto standard. If yes, we'll do it similarly.

**Comment by leahneukirchen** [comment]
Pretty surely, note that the other install rules install into INSTALL_ROOT as well.

**Comment by leahneukirchen** [comment]
There's also code missing to create this example directory, I think?

**Comment by kovzol** [comment]
Please let me know if that's OK.
