### ISSUE TITLE
[PATCH] xaos 3.6 doesn't build on i686

### ISSUE THREAD

**Issue by EricBelanger** [xaos-project/XaoS#67]
xaos 3.6 (3.5 had same problem) doesn't build on i686 architecture:

gcc -march=i686 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4    -I/usr/include -fomit-frame-pointer -DSFFE_USING -DSFFE_CMPLX_GSL -I/build/xaos/src/xaos-3.6/src/include -D_FORTIFY_SOURCE=2  -c -o zoom.o zoom.c
zoom.c:156:18: error: conflicting types for 'fillline_8'
 #define fillline fillline_8
                  ^
zoomd.c:283:20: note: in expansion of macro 'fillline'
 static INLINE void fillline(int line)
                    ^
zoom.c:144:13: note: previous declaration of 'fillline_8' was here
 static void fillline_8(int line) REGISTERS(0);
             ^ 
zoom.c:163:18: error: conflicting types for 'fillline_32'
 #define fillline fillline_32
                  ^
zoomd.c:283:20: note: in expansion of macro 'fillline'
 static INLINE void fillline(int line)
                    ^
zoom.c:147:13: note: previous declaration of 'fillline_32' was here
 static void fillline_32(int line) REGISTERS(0);
             ^ 
zoom.c:170:18: error: conflicting types for 'fillline_24'
 #define fillline fillline_24
                  ^
zoomd.c:283:20: note: in expansion of macro 'fillline'
 static INLINE void fillline(int line)
                    ^
zoom.c:146:13: note: previous declaration of 'fillline_24' was here
 static void fillline_24(int line) REGISTERS(0);
             ^ 
zoom.c:177:18: error: conflicting types for 'fillline_16'
 #define fillline fillline_16
                  ^
zoomd.c:283:20: note: in expansion of macro 'fillline'
 static INLINE void fillline(int line)
                    ^
zoom.c:145:13: note: previous declaration of 'fillline_16' was here
 static void fillline_16(int line) REGISTERS(0);
             ^ 
zoom.c:937:1: error: conflicting types for 'moveoldpoints'
 moveoldpoints(void /_@unused@ */ *data1,
 ^  
zoom.c:142:1: note: previous declaration of 'moveoldpoints' was here
 moveoldpoints(void *data1, struct taskinfo *task, int r1, int r2)
 ^  
<builtin>: recipe for target 'zoom.o' failed
make[2]: *_\* [zoom.o] Error 1
# The following patch fix the issue:

--- xaos-3.5/src/engine/zoomd.c.orig    2009-07-18 00:50:31.000000000 +0100
+++ xaos-3.5/src/engine/zoomd.c 2012-05-20 19:04:55.891065437 +0100
@@ -280,6 +280,7 @@ dosymetry2(void /*@unused@ */ *data, str
 #endif
 #undef bpp1

+REGISTERS(0)
 static INLINE void fillline(int line)
 {
     register unsigned char _RESTRICT vbuff = cimage.currlines[line];
--- xaos-3.5/src/engine/zoom.c.fix-build        2009-07-18 00:50:31.000000000 +0100
+++ xaos-3.5/src/engine/zoom.c  2012-05-20 19:11:53.625083113 +0100
@@ -933,6 +933,7 @@ static /_INLINE */ void preparemoveoldpo
 }

 #ifndef USE_i386ASM
+REGISTERS(0)
 static /_INLINE */ void
 moveoldpoints(void /_@unused@ _/ *data1,
              struct taskinfo /_@unused@ */ *task,

**Comment by jblang** [comment]
Already fixed by 4ae95a56c4ed597b5e8cd7c8fd183755451c78f0
