### ISSUE TITLE
Please create an AppData file for XaoS

### ISSUE THREAD

**Issue by hughsie** [xaos-project/XaoS#69]
Please consider writing and installing an AppData file with the application description and some screenshots, else XaoS looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't. See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by kovzol** [comment]
https://github.com/xaos-project/XaoS/commit/3770e97b56d42bfebb162f3c8d9c8a6ff8aa1763 addresses this. Please check, thanks!

**Comment by kanurag94** [comment]
Closing this issue, as per above comment. Please re-open if there is something to add. :)
