### ISSUE TITLE
Access Violation in 3dd.c

### ISSUE THREAD

**Issue by ariccio** [xaos-project/XaoS#70]
With Application Verifier enabled, turning on `Autopilot` and subsequently enabling `Pseudo 3d` triggers an Access Violation in `3dd.c` at line `62`.

I'm not familiar with the architecture of Xaos, but it seems like you're reading a few bytes past the end of a buffer.

See https://www.youtube.com/watch?v=F1vOa9D9rSQ for a screencapture of the bug in action.

**Comment by jblang** [comment]
I was not able to reproduce this using the latest build of XaoS on Windows (built using MinGW 32-bit via MSYS2).  I see from the youtube video you were using Visual Studio to debug it. I assume that means you also compiled it using Microsoft's C compiler?

**Comment by jblang** [comment]
I was able to reproduce this after compiling XaoS with Visual Studio.  I will see if I can figure this out, time permitting, but since Visual Studio isn't the official way we compile XaoS for Windows, it is not a priority.

**Comment by jblang** [comment]
I am even less inclined at this point to spend time trying to get XaoS compiling with Visual Studio. We are standardizing on Qt and mingw for windows builds.
