### ISSUE TITLE
(minor) redundant `const` in render.c

### ISSUE THREAD

**Issue by ariccio** [xaos-project/XaoS#71]
At line `580` in `render.c`, parameter 3 of function `uih_renderimage` is defined as `const xio_constpath path`. In `ui_helper.h`, at line `535`, parameter 3 of function `uih_renderimage` is declared as `xio_constpath path`.

Lastly, `xio_constpath` is `typedef`'d as `typedef const char *xio_constpath`.

**Comment by jblang** [comment]
Fixed
