### ISSUE TITLE
Possible NULL pointer dereference in dialog.c, line 486

### ISSUE THREAD

**Issue by ariccio** [xaos-project/XaoS#74]
If malloc fails in:

```
    char *c = (char *) malloc(d->ndisplayed + 2);
    strncpy(c, d->text + d->start, d->ndisplayed);
```

then strncpy may dereference a NULL pointer.

**Comment by jblang** [comment]
Well, there is stuff like this all over the code.  I found 101 uses of malloc and we almost never check to see if it succeeded.  I think we're OK with XaoS crashing if malloc fails.
