### ISSUE TITLE
Loading a Random Example Doesn't Work on macOS

### ISSUE THREAD

**Issue by the-real-tokai** [xaos-project/XaoS#83]
Loading a random example via the `File` > `Load random example` function does not work anymore with the current version. Just a red error message pops up: `Error: could not open examples`.

**XaoS 3.5** on **OS X 10.10.5**

**Comment by jblang** [comment]
Unfortunately I don't have a Mac that I can test this on or develop a fix.  We need a new Mac maintainer.  I can provide guidance for anyone who volunteers.

**Comment by jblang** [comment]
This will be fixed once we do the next release.
