### ISSUE TITLE
Window managers cause segfaults

### ISSUE THREAD

**Issue by mar77i** [xaos-project/XaoS#86]
My window manager (dwm) puts windows into monocle view when they're created. This crashed XaoS in that it called alloc_image with a 640x480 image, but later in `xalloc_display` uses the much diverging values of `xdisplay *new`'s width and height members.

It was quite a confusing search, because the bytes per line weren't even close to depth times width.

This patch solves the issue for me, currently:
```
diff --git a/src/ui/ui-drv/x11/ui_x11.c b/src/ui/ui-drv/x11/ui_x11.c
index 8034953..5471405 100644
--- a/src/ui/ui-drv/x11/ui_x11.c
+++ b/src/ui/ui-drv/x11/ui_x11.c
@@ -402,6 +402,8 @@ static int x11_init(void)
     replay = XCreateFontCursor(d->display, XC_dot);
     if (d->truecolor || d->privatecolormap)
    x11_driver.flags &= ~RANDOM_PALETTE_SIZE;
+   XSync(d->display, 0);
+   xupdate_size(d);
     if (!alloc_image(d)) {
    xfree_display(d);
    return (0);
```

**Comment by binaryplease** [comment]
Xaos segfaults upon start on i3, might be related.

```
xaos -config
XaoS configuration
Version:   3.6
Type size: 16
integer size: 4
configfile: .XaoSrc
using alloca
using long double
using gettimeofday
using ftime
assertions disabled
user formula evaluation

Available drivers: X11, aa
```

**Comment by mar77i** [comment]
Most likely is. DId you try with my patch?

**Comment by binaryplease** [comment]
@mar77i I cloned the repo and edited the file as shown, but don't really know how to compile the application. Is it just running "make" ?

**Comment by binaryplease** [comment]
@mar77i Yes, I applied it and it solves the problem.
Future reference:
- edit file as shown above
- run ./configure
- run make
- execute ./bin/xaos


Could this be merged?

**Comment by jblang** [comment]
I'm looking at the patch now. I will get it committed soon.

I think this [debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=452284) might also be the same issue.

**Comment by jblang** [comment]
Fix is tested and committed. Thanks!
