### ISSUE TITLE
XaoS 3.6 incorrectly shows version 3.5 in Finder on macOS

### ISSUE THREAD

**Issue by core-code** [xaos-project/XaoS#91]
i've downloaded Version '3.6' but when selecting it in the Finder and using 'Get Info' it shows Version '3.5'

**Comment by jblang** [comment]
Version 3.6 was developed in a hurry on a borrowed Mac so I could fix the zooming issue that 3.5 had on the newer versions of Mac OS X.  Help is not working correctly either, IIRC.  I no longer have a Mac available to develop on, so we really need volunteers for a Mac maintainer.

**Comment by jblang** [comment]
This will be fixed once we do the next release.

**Comment by core-code** [comment]
thanks
