### ISSUE TITLE
Installation of docs: No such file or directory

### ISSUE THREAD

**Issue by glixx** [xaos-project/XaoS#97]
/usr/bin/install: cannot stat 'AUTHORS': No such file or directory
/usr/bin/install: cannot stat 'INSTALL': No such file or directory
/usr/bin/install: cannot stat 'doc/xaos.info': No such file or directory

**Comment by jblang** [comment]
The Makefiles need to be updated. I moved AUTHORS to CREDITS.md, INSTALL to INSTALL.md, and xaos.info has been removed entirely because the docs are now online in GitHub's Wiki.

**Comment by jblang** [comment]
Fixed
