### ISSUE TITLE
spurious-executable-perm

### ISSUE THREAD

**Issue by glixx** [xaos-project/XaoS#98]
xaos-debuginfo.x86_64: W: spurious-executable-perm /usr/src/debug/xaos-3.6/src/engine/zoom.c

xaos-debuginfo.x86_64: W: spurious-executable-perm /usr/src/debug/xaos-3.6/src/engine/zoomd.c

**Comment by jblang** [comment]
Can you provide more details where you saw this? Compiler and OS version?  Is it when you were compiling it, or running it?

**Comment by glixx** [comment]
This is warning of rpmlint.
Just needs to run:
```
chmod -x src/engine/zoom.c
chmod -x src/engine/zoomd.c
```
cause .c code cannot be executable.

**Comment by jblang** [comment]
Fixed.
